import { Component, OnInit<% if(!!viewEncapsulation) { %>, ViewEncapsulation<% }%><% if(changeDetection !== 'Default') { %>, ChangeDetectionStrategy<% }%> } from '@angular/core';

import { TreeNode } from 'primeng/api';

@Component({
  selector: '<%= selector %>',<% if(inlineTemplate) { %>
  template: `<p-treeTable [value]="files1">
                <ng-template pTemplate="header">
                  <tr>
                    <th>Name</th>
                    <th>Size</th>
                    <th>Type</th>
                  </tr>
                </ng-template>
                <ng-template pTemplate="body" let-rowNode let-rowData="rowData">
                  <tr>
                    <td>
                      <p-treeTableToggler [rowNode]="rowNode"></p-treeTableToggler>
                      {{rowData.name}}
                    </td>
                    <td>{{rowData.size}}</td>
                    <td>{{rowData.type}}</td>
                  </tr>            
                 </ng-template>
               </p-treeTable>`,<% } else { %>
  templateUrl: './<%= dasherize(name) %>.component.html',<% } if(inlineStyle) { %>
  styles: []<% } else { %>
  styleUrls: ['./<%= dasherize(name) %>.component.<%= styleext %>']<% } %><% if(!!viewEncapsulation) { %>,
  encapsulation: ViewEncapsulation.<%= viewEncapsulation %><% } if (changeDetection !== 'Default') { %>,
  changeDetection: ChangeDetectionStrategy.<%= changeDetection %><% } %>
})
export class <%= classify(name) %>Component implements OnInit {
  files1: TreeNode[];
  cols: any[];
  
  ngOnInit() {
    this.files1 = {
      "data":
      [  
          {  
              "data":{  
                  "name":"Applications",
                  "size":"200mb",
                  "type":"Folder"
              },
              "children":[  
                  {  
                      "data":{  
                          "name":"Angular",
                          "size":"25mb",
                          "type":"Folder"
                      },
                      "children":[  
                          {  
                              "data":{  
                                  "name":"angular.app",
                                  "size":"10mb",
                                  "type":"Application"
                              }
                          },
                          {  
                              "data":{  
                                  "name":"cli.app",
                                  "size":"10mb",
                                  "type":"Application"
                              }
                          },
                          {  
                              "data":{  
                                  "name":"mobile.app",
                                  "size":"5mb",
                                  "type":"Application"
                              }
                          }
                      ]
                  },
                  {  
                      "data":{  
                          "name":"editor.app",
                          "size":"25mb",
                          "type":"Application"
                      }
                  },
                  {  
                      "data":{  
                          "name":"settings.app",
                          "size":"50mb",
                          "type":"Application"
                      }
                  }
              ]
          },
          {  
              "data":{  
                  "name":"Cloud",
                  "size":"20mb",
                  "type":"Folder"
              },
              "children":[  
                  {  
                      "data":{  
                          "name":"backup-1.zip",
                          "size":"10mb",
                          "type":"Zip"
                      }
                  },
                  {  
                      "data":{  
                          "name":"backup-2.zip",
                          "size":"10mb",
                          "type":"Zip"
                      }
                  }
              ]
          },
          {  
              "data": {  
                  "name":"Desktop",
                  "size":"150kb",
                  "type":"Folder"
              },
              "children":[  
                  {  
                      "data":{  
                          "name":"note-meeting.txt",
                          "size":"50kb",
                          "type":"Text"
                      }
                  },
                  {  
                      "data":{  
                          "name":"note-todo.txt",
                          "size":"100kb",
                          "type":"Text"
                      }
                  }
              ]
          },
          {  
              "data":{  
                  "name":"Documents",
                  "size":"75kb",
                  "type":"Folder"
              },
              "children":[
                  {  
                      "data":{  
                          "name":"Work",
                          "size":"55kb",
                          "type":"Folder"
                      },
                      "children":[  
                          {  
                              "data":{  
                                  "name":"Expenses.doc",
                                  "size":"30kb",
                                  "type":"Document"
                              }
                          },
                          {  
                              "data":{  
                                  "name":"Resume.doc",
                                  "size":"25kb",
                                  "type":"Resume"
                              }
                          }
                      ]
                  },
                  {  
                      "data":{  
                          "name":"Home",
                          "size":"20kb",
                          "type":"Folder"
                      },
                      "children":[  
                          {  
                              "data":{  
                                  "name":"Invoices",
                                  "size":"20kb",
                                  "type":"Text"
                              }
                          }
                      ]
                  }
              ]
          },
          {  
              "data": {  
                  "name":"Downloads",
                  "size":"25mb",
                  "type":"Folder"
              },
              "children":[  
                  {  
                      "data": {  
                          "name":"Spanish",
                          "size":"10mb",
                          "type":"Folder"
                      },
                      "children":[  
                          {  
                              "data":{  
                                  "name":"tutorial-a1.txt",
                                  "size":"5mb",
                                  "type":"Text"
                              }
                          },
                          {  
                              "data":{  
                                  "name":"tutorial-a2.txt",
                                  "size":"5mb",
                                  "type":"Text"
                              }
                          }
                      ]
                  },
                  {  
                      "data":{  
                          "name":"Travel",
                          "size":"15mb",
                          "type":"Text"
                      },
                      "children":[  
                          {  
                              "data":{  
                                  "name":"Hotel.pdf",
                                  "size":"10mb",
                                  "type":"PDF"
                              }
                          },
                          {  
                              "data":{  
                                  "name":"Flight.pdf",
                                  "size":"5mb",
                                  "type":"PDF"
                              }
                          }
                      ]
                  }
              ]
          },
          {  
              "data": {  
                  "name":"Main",
                  "size":"50mb",
                  "type":"Folder"
              },
              "children":[  
                  {  
                      "data":{  
                          "name":"bin",
                          "size":"50kb",
                          "type":"Link"
                      }
                  },
                  {  
                      "data":{  
                          "name":"etc",
                          "size":"100kb",
                          "type":"Link"
                      }
                  },
                  {  
                      "data":{  
                          "name":"var",
                          "size":"100kb",
                          "type":"Link"
                      }
                  }
              ]
          },
          {  
              "data":{  
                  "name":"Other",
                  "size":"5mb",
                  "type":"Folder"
              },
              "children":[  
                  {  
                      "data":{  
                          "name":"todo.txt",
                          "size":"3mb",
                          "type":"Text"
                      }
                  },
                  {  
                      "data":{  
                          "name":"logo.png",
                          "size":"2mb",
                          "type":"Picture"
                      }
                  }
              ]
          },
          {  
              "data":{  
                  "name":"Pictures",
                  "size":"150kb",
                  "type":"Folder"
              },
              "children":[  
                  {  
                      "data":{  
                          "name":"barcelona.jpg",
                          "size":"90kb",
                          "type":"Picture"
                      }
                  },
                  {  
                      "data":{  
                          "name":"primeng.png",
                          "size":"30kb",
                          "type":"Picture"
                      }
                  },
                  {  
                      "data":{  
                          "name":"prime.jpg",
                          "size":"30kb",
                          "type":"Picture"
                      }
                  }
              ]
          },
          {  
              "data":{  
                  "name":"Videos",
                  "size":"1500mb",
                  "type":"Folder"
              },
              "children":[  
                  {  
                      "data":{  
                          "name":"primefaces.mkv",
                          "size":"1000mb",
                          "type":"Video"
                      }
                  },
                  {  
                      "data":{  
                          "name":"intro.avi",
                          "size":"500mb",
                          "type":"Video"
                      }
                  }
              ]
          }
      ]
  }.data;

    this.cols = [
      { field: 'name', header: 'Name' },
      { field: 'size', header: 'Size' },
      { field: 'type', header: 'Type' }
    ];
}
}